import type { Theme, ThemeType } from '../types';

export const themes: Record<ThemeType, Theme> = {
  professional: {
    name: 'Professional',
    colors: {
      background: '#ffffff',
      taskBar: '#3b82f6',
      taskBarComplete: '#1d4ed8',
      taskBarText: '#ffffff',
      gridLine: '#e5e7eb',
      todayLine: '#ef4444',
      weekend: '#f9fafb',
      header: '#f3f4f6',
      headerText: '#1f2937',
      text: '#374151',
      border: '#d1d5db',
      dependency: '#6b7280',
    },
  },
  modern: {
    name: 'Modern',
    colors: {
      background: '#fafafa',
      taskBar: '#8b5cf6',
      taskBarComplete: '#6d28d9',
      taskBarText: '#ffffff',
      gridLine: '#e4e4e7',
      todayLine: '#f59e0b',
      weekend: '#f4f4f5',
      header: '#18181b',
      headerText: '#fafafa',
      text: '#27272a',
      border: '#d4d4d8',
      dependency: '#71717a',
    },
  },
  colorful: {
    name: 'Colorful',
    colors: {
      background: '#fef3c7',
      taskBar: '#ec4899',
      taskBarComplete: '#be185d',
      taskBarText: '#ffffff',
      gridLine: '#fde68a',
      todayLine: '#10b981',
      weekend: '#fef9c3',
      header: '#7c3aed',
      headerText: '#ffffff',
      text: '#713f12',
      border: '#fbbf24',
      dependency: '#a855f7',
    },
  },
  dark: {
    name: 'Dark',
    colors: {
      background: '#1f2937',
      taskBar: '#60a5fa',
      taskBarComplete: '#3b82f6',
      taskBarText: '#ffffff',
      gridLine: '#374151',
      todayLine: '#f87171',
      weekend: '#111827',
      header: '#111827',
      headerText: '#f3f4f6',
      text: '#e5e7eb',
      border: '#4b5563',
      dependency: '#9ca3af',
    },
  },
  minimal: {
    name: 'Minimal',
    colors: {
      background: '#ffffff',
      taskBar: '#000000',
      taskBarComplete: '#404040',
      taskBarText: '#ffffff',
      gridLine: '#f5f5f5',
      todayLine: '#737373',
      weekend: '#fafafa',
      header: '#ffffff',
      headerText: '#000000',
      text: '#404040',
      border: '#e5e5e5',
      dependency: '#a3a3a3',
    },
  },
};
