import type { Task } from '../types';

export const sampleTasks: Task[] = [
  {
    id: '1',
    title: 'Project Planning',
    startDate: new Date(2025, 10, 10),
    endDate: new Date(2025, 10, 15),
    progress: 100,
    assignee: 'Alice Johnson',
    color: '#3b82f6',
    description: 'Initial project planning and requirements gathering',
  },
  {
    id: '2',
    title: 'Design Phase',
    startDate: new Date(2025, 10, 16),
    endDate: new Date(2025, 10, 25),
    progress: 80,
    assignee: 'Bob Smith',
    dependencies: ['1'],
    color: '#8b5cf6',
    description: 'UI/UX design and wireframing',
  },
  {
    id: '3',
    title: 'Frontend Development',
    startDate: new Date(2025, 10, 20),
    endDate: new Date(2025, 11, 10),
    progress: 45,
    assignee: 'Carol White',
    dependencies: ['2'],
    color: '#10b981',
    description: 'Build React components and user interface',
  },
  {
    id: '4',
    title: 'Backend Development',
    startDate: new Date(2025, 10, 20),
    endDate: new Date(2025, 11, 8),
    progress: 50,
    assignee: 'David Brown',
    dependencies: ['2'],
    color: '#f59e0b',
    description: 'API development and database setup',
  },
  {
    id: '5',
    title: 'Integration Testing',
    startDate: new Date(2025, 11, 11),
    endDate: new Date(2025, 11, 18),
    progress: 0,
    assignee: 'Eve Davis',
    dependencies: ['3', '4'],
    color: '#ef4444',
    description: 'Test integration between frontend and backend',
  },
  {
    id: '6',
    title: 'User Acceptance Testing',
    startDate: new Date(2025, 11, 19),
    endDate: new Date(2025, 11, 25),
    progress: 0,
    assignee: 'Frank Miller',
    dependencies: ['5'],
    color: '#ec4899',
    description: 'End user testing and feedback collection',
  },
  {
    id: '7',
    title: 'Deployment',
    startDate: new Date(2025, 11, 26),
    endDate: new Date(2025, 11, 28),
    progress: 0,
    assignee: 'Alice Johnson',
    dependencies: ['6'],
    color: '#06b6d4',
    description: 'Deploy to production environment',
  },
];

export const projectTemplates = {
  softwareDevelopment: {
    name: 'Software Development',
    tasks: sampleTasks,
  },
  marketing: {
    name: 'Marketing Campaign',
    tasks: [
      {
        id: '1',
        title: 'Market Research',
        startDate: new Date(2025, 10, 8),
        endDate: new Date(2025, 10, 15),
        progress: 100,
        assignee: 'Marketing Team',
        color: '#3b82f6',
      },
      {
        id: '2',
        title: 'Campaign Strategy',
        startDate: new Date(2025, 10, 16),
        endDate: new Date(2025, 10, 22),
        progress: 75,
        assignee: 'Strategy Lead',
        dependencies: ['1'],
        color: '#8b5cf6',
      },
      {
        id: '3',
        title: 'Content Creation',
        startDate: new Date(2025, 10, 23),
        endDate: new Date(2025, 11, 5),
        progress: 40,
        assignee: 'Content Team',
        dependencies: ['2'],
        color: '#10b981',
      },
      {
        id: '4',
        title: 'Campaign Launch',
        startDate: new Date(2025, 11, 6),
        endDate: new Date(2025, 11, 12),
        progress: 0,
        assignee: 'Campaign Manager',
        dependencies: ['3'],
        color: '#f59e0b',
      },
      {
        id: '5',
        title: 'Performance Analysis',
        startDate: new Date(2025, 11, 13),
        endDate: new Date(2025, 11, 20),
        progress: 0,
        assignee: 'Analytics Team',
        dependencies: ['4'],
        color: '#ef4444',
      },
    ] as Task[],
  },
  construction: {
    name: 'Construction Project',
    tasks: [
      {
        id: '1',
        title: 'Site Preparation',
        startDate: new Date(2025, 10, 8),
        endDate: new Date(2025, 10, 20),
        progress: 100,
        assignee: 'Site Team',
        color: '#3b82f6',
      },
      {
        id: '2',
        title: 'Foundation',
        startDate: new Date(2025, 10, 21),
        endDate: new Date(2025, 11, 5),
        progress: 60,
        assignee: 'Foundation Crew',
        dependencies: ['1'],
        color: '#8b5cf6',
      },
      {
        id: '3',
        title: 'Framing',
        startDate: new Date(2025, 11, 6),
        endDate: new Date(2025, 11, 20),
        progress: 0,
        assignee: 'Framing Team',
        dependencies: ['2'],
        color: '#10b981',
      },
      {
        id: '4',
        title: 'Electrical & Plumbing',
        startDate: new Date(2025, 11, 21),
        endDate: new Date(2026, 0, 10),
        progress: 0,
        assignee: 'MEP Team',
        dependencies: ['3'],
        color: '#f59e0b',
      },
      {
        id: '5',
        title: 'Finishing',
        startDate: new Date(2026, 0, 11),
        endDate: new Date(2026, 0, 25),
        progress: 0,
        assignee: 'Finishing Team',
        dependencies: ['4'],
        color: '#ef4444',
      },
    ] as Task[],
  },
};
